### ISSUE TITLE
unable to install / start / reindex

### ISSUE THREAD

**Issue by mashpie** [dkd/redsun#2]
followed your instructions, but got errors with 

```
$ bundle exec sunspot:solr:start
...
bundler: command not found: sunspot:solr:start
...
```

had to change to

```
$ RAILS_ENV=production bundle exec rake sunspot:solr:start

  Note: This task has been moved to the sunspot_solr gem. To install, start and
  stop a local Solr instance, please add sunspot_solr to your Gemfile:

  group :development do
    gem 'sunspot_solr'
  end
```

aha, well... yes that is added in your Gemfile, ok next:

```
$ RAILS_ENV=production bundle exec rake sunspot:solr:reindex

rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
...
URI: http://localhost:8080/solr/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:Project</query></delete>"
...
```

and a backtrace

```
Backtrace: /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:82:in `update'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:146:in `delete_by_query'/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:82:in `update'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rsolr-1.0.13/lib/rsolr/client.rb:146:in `delete_by_query'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/indexer.rb:68:in `remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session.rb:197:in `block in remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session.rb:197:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session.rb:197:in `remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot.rb:502:in `remove_all'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/class_set.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot-2.2.2/lib/sunspot/class_set.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/tasks.rb:71:in `with_session'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sunspot_rails-2.2.2/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sunspot:solr:reindex => sunspot:reindex
(See full trace by running task with --trace)
```

any hints?

Installed Solr/Tomcat as per https://www.digitalocean.com/community/tutorials/how-to-install-solr-on-ubuntu-14-04

**Comment by KieranHayes** [comment]
I updated the documentation to include the missing rake command.

You should see within  Redmine's config folder a file named sunspot.yml

Here you have to make sure that host and path to your Solr-core are correct.

```
production:
  solr:
    hostname: 127.0.0.1
    port: 8080
    log_level: WARNING
    path: /solr-4.10.4/name-of-your-solr-core
```

If you have access to your solr admin panel, then you should be able to connect to the core. 
If you manage to fix the connection issue then you will probably run into schema issues. You have to make sure that you are using the schema.xml from the sunspot gem in your Solr-Core.

There is an outdated guide here: https://github.com/sunspot/sunspot/wiki/Ubuntu-10.04-lts-server (see 37)

**Comment by mashpie** [comment]
I bet this is the real issue:

> You have to make sure that you are using the schema.xml from the sunspot gem in your Solr-Core.

quote from 37. 

> paste the contents of the file that is generated by sunspot

where should that schema file get generated?

**Comment by KieranHayes** [comment]
You can grab a  schema.xml over here: https://github.com/sunspot/sunspot/tree/v2.2.5/sunspot_solr/solr/solr/configsets/sunspot/conf

Just make sure that you it it's compatible with your Solr-Server. If you are using a version < 5 it makes sense to browse back in history to grab a compatible file: https://github.com/sunspot/sunspot/tree/v2.2.0/sunspot_solr/solr/solr/conf
